- hosts: ndfc
  gather_facts: no
  connection: ansible.netcommon.httpapi

  tasks:
  - name: Gather List of Fabrics from NDFC
    cisco.dcnm.dcnm_rest:
      method: GET
      path: /appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics
    register: fabrics
  
  - debug:
      var: fabrics
